version: "3.1"

services:
  singlelink-client:
    image: neutroncreative/singlelink-editor:latest
    build:
      context: client
      dockerfile: client.Dockerfile
    environment:
      - HOSTNAME
      - API_URL
    ports:
      - "80:80"
    expose:
      - "80"
  singlelink-server:
    image: neutroncreative/singlelink-server:latest
    build:
      context: server
      dockerfile: server.Dockerfile
    environment:
      - DATABASE
      - SECRET
      - CAPTURE_KEY
      - HOST
      - PORT
      - API_DOMAIN
      - CLIENT_DOMAIN
      - CONTACT_EMAIL
      - AWS_SENDER_EMAIL_ADDRESS
      - AWS_REGION
      - AWS_ACCESS_KEY
      - AWS_SECRET_KEY
      - S3_ENDPOINT
      - S3_BUCKETNAME
      - S3_PORT
      - S3_USE_SSL
      - S3_ACCESS_KEY
      - S3_SECRET_KEY
      - MIXPANEL_TOKEN
      - DELETE_ADDON_INSTALLS_THRESHOLD
    ports:
      - "5566:80"
    expose:
      - "5566"
